cookie:
  expiry_days: 30
  key: report_automation_cookie
  name: report_automation_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$eAB2tsoSpQTVog92MOuqzed8lEGkOrs8qW.lgY8sx.0WPPMlGrOvO
preauthorized:
  emails:
  - melsby@gmail.com
